'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EMP
    Public Property ID As Decimal
    Public Property Emp_name As String
    Public Property Emp_Nat As String
    Public Property Emp_Gender As String
    Public Property Data_Of_Birth As Nullable(Of Date)
    Public Property Mobile As Nullable(Of Decimal)
    Public Property Email As String
    Public Property Branch As String
    Public Property nat_id As Nullable(Of Decimal)

End Class
