'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property ID_stu As Decimal
    Public Property stu_name As String
    Public Property stu_Nat As String
    Public Property stu_Gender As String
    Public Property stu_Birth As Nullable(Of Date)
    Public Property stu_Mobile As Nullable(Of Decimal)
    Public Property stu_Email As String
    Public Property uni_Branch As String

End Class
